#!/usr/bin/env node
/**
 * build-head.js — normalise the <head> (and the no-JS fallback) of every page.
 *
 * Every page in this repo is hand-written or generated from a different script,
 * so the <head> drifted: no favicon anywhere, theme-color on 14 of 222 pages,
 * Open Graph tags on 10, and nothing at all telling a phone browser which colour
 * scheme we support or that we honour the OS text-size setting. This script owns
 * that shared block so it is identical everywhere and self-correcting.
 *
 * What it manages, per page:
 *   - a HEAD:START/HEAD:END block just before </head> containing
 *     colour-scheme + theme-color, the OS text-scaling opt-in, the icon set,
 *     the web manifest, and Open Graph / Twitter tags derived from the page's
 *     own <title>, <meta description> and <link rel=canonical>;
 *   - a NOSCRIPT:START/NOSCRIPT:END banner right after <body> on pages whose
 *     content is hidden until JavaScript runs (they render blank otherwise).
 *
 * It only ever rewrites its own blocks plus the duplicate tags it supersedes, so
 * it is idempotent and safe to re-run. It must run LAST in the generator chain
 * (after build-hub / build-topic-pages / build-review-pages), because those
 * scripts rewrite whole files and would drop the block.
 *
 * Run: node scripts/build-head.js  [--check]
 *   --check  exit 1 if anything would change (used to verify a clean tree)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://activities.englishonline.training';
const THEME = '#1a3a5c';
const CHECK = process.argv.includes('--check');

// Pages that render blank without JavaScript: everything on the shared framework
// (.step is display:none until showStep runs) plus the standalone interactive
// pages, which hide .screen / .exercise / .game-panel the same way.
const HIDDEN_CONTAINER = /\.(step|screen|exercise|game-panel)\b[^{}]*\{[^{}]*display:\s*none/;

function esc(s) {
  return String(s).replace(/&(?![a-zA-Z#0-9]+;)/g, '&amp;').replace(/"/g, '&quot;');
}

function firstMatch(html, re, group = 1) {
  const m = html.match(re);
  return m ? m[group].trim() : '';
}

/** Tags this script owns — stripped wherever they appear so we never duplicate. */
const SUPERSEDED = [
  /[ \t]*<meta\s+name=["'](?:theme-color|color-scheme|text-scale|twitter:[a-z:]+)["'][^>]*>\s*\n?/gi,
  /[ \t]*<meta\s+(?:property|name)=["']og:[a-z:_]+["'][^>]*>\s*\n?/gi,
  /[ \t]*<link\s+rel=["'](?:icon|shortcut icon|apple-touch-icon|manifest)["'][^>]*>\s*\n?/gi,
];

// --- skip link + main landmark (for pages not served by exercise.js) --------
// exercise.js already injects a skip link and marks the active .step as the main
// landmark on the 167 framework pages. The rest — Abitur packs, lead magnets, the
// standalone uni tasks, the themen/ topic pages — had neither, so a keyboard user
// had to tab through the whole header on every visit.
// Same look as the one exercise.js injects on framework pages, so the site has
// one skip link, not two designs.
const SKIP_STYLE = `<style id="eol-skip-style">.eol-skip{position:absolute;left:.5rem;top:-3rem;z-index:1000;` +
  `background:var(--gold,#c9a227);color:#1a1a1a;font-weight:700;padding:.5rem 1rem;border-radius:8px;` +
  `text-decoration:none;transition:top .2s;font-family:'Segoe UI',system-ui,sans-serif}` +
  `.eol-skip:focus{top:.5rem}@media(prefers-reduced-motion:reduce){.eol-skip{transition:none}}</style>`;

const SKIP_LINK = `<!-- SKIP:START — generated by scripts/build-head.js, do not edit by hand -->
<a class="eol-skip" href="#main">Zum Inhalt springen / Skip to content</a>
<!-- SKIP:END -->
`;

/**
 * Give the page a main landmark with id="main", if one can be identified with
 * confidence. Returns the updated html, or null when there is no obvious target
 * (those pages are reported so they can be handled by hand).
 */
function ensureMainLandmark(html) {
  if (/\bid=["']main["']/.test(html)) return html;

  const mainTag = html.match(/<main\b([^>]*)>/i);
  if (mainTag) return html.replace(mainTag[0], `<main id="main"${mainTag[1]}>`);

  // No <main> element: promote the first content wrapper after the header to a
  // main landmark by role. Same approach exercise.js takes with .step, and it
  // avoids rewriting a </div> whose match we cannot see from a regex.
  const wrapper = html.match(/(?:<\/header>|<body[^>]*>)\s*(?:<!--[\s\S]*?-->\s*)*(<div class="(?:wrap|container)[^"]*">)/i);
  if (wrapper) return html.replace(wrapper[1], wrapper[1].replace('<div ', '<div id="main" role="main" '));

  return null;
}

function headBlock(file, html, withSkipStyle) {
  const rel = file.includes('/') ? '../' : '';
  const lang = firstMatch(html, /<html[^>]*\blang=["']([^"']+)["']/i) || 'en';
  const rawTitle = firstMatch(html, /<title>([\s\S]*?)<\/title>/i);
  const title = rawTitle.replace(/\s*[|·—-]\s*(?:EnglishOnline\.training|englishonline\.training)\s*$/i, '').trim();
  // Match the closing quote by backreference: descriptions contain apostrophes
  // ("New York's boroughs"), which a [^"']* class would cut the value short at.
  const desc = firstMatch(html, /<meta\s+name=["']description["']\s+content=(["'])([\s\S]*?)\1/i, 2);
  const canonical = firstMatch(html, /<link\s+rel=["']canonical["']\s+href=(["'])([\s\S]*?)\1/i, 2);

  const lines = [
    '<!-- HEAD:START — generated by scripts/build-head.js, do not edit by hand -->',
    // Tell the browser which schemes we actually support, so mobile dark modes
    // stop auto-inverting a light design into unreadable mud.
    '<meta name="color-scheme" content="light">',
    `<meta name="theme-color" content="${THEME}">`,
    // Opt in to the OS/browser text-size setting on mobile (rem/em scale, px does not).
    '<meta name="text-scale" content="scale">',
    `<link rel="icon" href="${rel}favicon.ico" sizes="32x32">`,
    `<link rel="icon" href="${rel}icon.svg" type="image/svg+xml">`,
    `<link rel="apple-touch-icon" href="${rel}apple-touch-icon.png">`,
    `<link rel="manifest" href="${rel}site.webmanifest">`,
    // The themen/ pages are explanatory articles; everything else is a page/app.
    `<meta property="og:type" content="${file.startsWith('themen/') ? 'article' : 'website'}">`,
    '<meta property="og:site_name" content="EnglishOnline.training">',
    `<meta property="og:locale" content="${lang.toLowerCase().startsWith('de') ? 'de_DE' : 'en_GB'}">`,
  ];
  if (title) lines.push(`<meta property="og:title" content="${esc(title)}">`);
  if (desc) lines.push(`<meta property="og:description" content="${esc(desc)}">`);
  if (canonical && !/TODO/i.test(canonical)) lines.push(`<meta property="og:url" content="${esc(canonical)}">`);
  lines.push(
    `<meta property="og:image" content="${SITE}/icon-512.png">`,
    '<meta property="og:image:alt" content="englishonline.training">',
    '<meta name="twitter:card" content="summary">'
  );
  if (withSkipStyle) lines.push(SKIP_STYLE);
  lines.push(
    '<!-- HEAD:END -->'
  );
  return lines.join('\n') + '\n';
}

const NOSCRIPT = `<!-- NOSCRIPT:START — generated by scripts/build-head.js, do not edit by hand -->
<noscript>
  <div style="background:#fdf3d8;border-bottom:2px solid #c9a227;color:#1d2b3a;padding:.9rem 1rem;font:1rem/1.5 'Segoe UI',system-ui,sans-serif;text-align:center">
    <strong lang="de">Diese Übung braucht JavaScript.</strong>
    <span lang="de">Bitte aktiviere JavaScript in deinem Browser — sonst bleiben die Aufgaben leer.</span>
    <br>
    <strong>This exercise needs JavaScript.</strong>
    <span>Please switch JavaScript on in your browser, otherwise the tasks stay empty.</span>
  </div>
</noscript>
<!-- NOSCRIPT:END -->
`;

function stripBlock(html, name) {
  return html.replace(new RegExp(`[ \\t]*<!-- ${name}:START[\\s\\S]*?${name}:END -->\\n?`, 'g'), '');
}

function processFile(file) {
  const abs = path.join(ROOT, file);
  const original = fs.readFileSync(abs, 'utf8');
  let html = ['HEAD', 'NOSCRIPT', 'SKIP'].reduce(stripBlock, original);

  const headEnd = html.search(/<\/head>/i);
  if (headEnd === -1) return { file, skipped: 'no <head>' };

  // Strip the tags this script now owns, but only inside <head> — the body may
  // legitimately contain e.g. an <img> we must not touch.
  let head = html.slice(0, headEnd);
  let rest = html.slice(headEnd);
  for (const re of SUPERSEDED) head = head.replace(re, '');

  // A viewport meta is not optional; one page never had one.
  if (!/<meta\s+name=["']viewport["']/i.test(head)) {
    head = head.replace(/(<meta\s+charset=[^>]*>\s*\n?)/i,
      '$1<meta name="viewport" content="width=device-width, initial-scale=1.0">\n');
  }

  html = head + rest;

  // exercise.js injects its own skip link; only the other pages need one here.
  const framework = /<script[^>]+src=["']\.{0,2}\/?exercise\.js/.test(html);
  let wantsSkip = !framework && !/class=["']skip-link["']/.test(html);
  let noLandmark = false;
  if (wantsSkip) {
    const withMain = ensureMainLandmark(html);
    if (withMain) html = withMain;
    else { wantsSkip = false; noLandmark = true; }
  }

  html = html.replace(/<\/head>/i, headBlock(file, html, wantsSkip) + '</head>');
  if (wantsSkip) html = html.replace(/(<body[^>]*>\n?)/i, (m) => m + SKIP_LINK);

  const needsNoscript = framework || HIDDEN_CONTAINER.test(html);
  if (needsNoscript) {
    html = html.replace(/(<body[^>]*>\n?)/i, (m) => m + NOSCRIPT);
  }

  if (!CHECK && html !== original) fs.writeFileSync(abs, html);
  return { file, changed: html !== original, noscript: needsNoscript, skip: wantsSkip, noLandmark };
}

const files = [
  ...fs.readdirSync(ROOT).filter((f) => f.endsWith('.html')),
  ...(fs.existsSync(path.join(ROOT, 'themen'))
    ? fs.readdirSync(path.join(ROOT, 'themen')).filter((f) => f.endsWith('.html')).map((f) => 'themen/' + f)
    : []),
].sort();

const results = files.map(processFile);
const changed = results.filter((r) => r.changed);
const skipped = results.filter((r) => r.skipped);
const withNoscript = results.filter((r) => r.noscript);
const withSkip = results.filter((r) => r.skip);
const noLandmark = results.filter((r) => r.noLandmark);

console.log(`build-head: ${files.length} pages scanned, ${changed.length} ${CHECK ? 'would change' : 'updated'}, ` +
  `${withNoscript.length} carry the no-JS banner, ${withSkip.length} got a skip link.`);
noLandmark.forEach((r) => console.log(`  no obvious main landmark, skip link not added: ${r.file}`));
skipped.forEach((r) => console.log(`  skipped ${r.file}: ${r.skipped}`));

if (CHECK && changed.length) {
  changed.slice(0, 20).forEach((r) => console.log('  stale: ' + r.file));
  process.exitCode = 1;
}
