#!/usr/bin/env node
/*
 * validate-data.js — shape checks for the data files the generators read.
 *
 *   node scripts/validate-data.js            data/topics.json + data/quizzes.json
 *   node scripts/validate-data.js --built    data/exercises.json  (scripts/check-exercises-data.js)
 *
 * explanations.json and the JSON-LD already have validators; these three had
 * none, so a typo did not fail anything. It silently broke a hub card, a topic
 * page or a quiz instead: a `related` slug with no page behind it, a quiz
 * `answer` that matches none of its options (unwinnable), a sub-heading that
 * says "ten questions" over nine.
 *
 * Two modes because the files have two lifecycles. topics.json and quizzes.json
 * are authored, so they are checked before the build (a VALIDATOR) and fail
 * fast. exercises.json is generated by build-exercise-data.js, so it is
 * checked after the build (a CHECKER) — checking the committed copy beforehand
 * would test the previous build, not this one.
 */
const fs = require('fs');
const path = require('path');
const { SITE, SKILL_LABELS } = require('./schema');

const ROOT = path.join(__dirname, '..');
const read = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8'));

const errors = [];
const fail = (where, msg) => errors.push(where + ': ' + msg);
const isStr = (v) => typeof v === 'string' && v.trim() !== '';
const isStrArr = (v) => Array.isArray(v) && v.every(isStr);
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function checkUnique(list, key, file) {
  const seen = new Set();
  list.forEach((x, i) => {
    if (seen.has(x[key])) fail(file + '[' + i + ']', 'duplicate ' + key + ' "' + x[key] + '"');
    seen.add(x[key]);
  });
}

// A multiple-choice item, in topics.json practice groups and in quizzes.json.
function checkChoice(item, where) {
  if (!isStr(item.q)) fail(where, 'no question text "q"');
  if (!isStrArr(item.options) || item.options.length < 2) {
    fail(where, '"options" must be at least two strings');
    return;
  }
  if (new Set(item.options).size !== item.options.length) fail(where, 'duplicate options');
  if (!item.options.includes(item.answer)) fail(where, '"answer" "' + item.answer + '" is not one of its options');
}

function topics() {
  const F = 'data/topics.json';
  const list = read(F);
  if (!Array.isArray(list)) return fail(F, 'must be an array');
  checkUnique(list, 'slug', F);
  const slugs = new Set(list.map((t) => t.slug));
  list.forEach((t, i) => {
    const w = F + ' ' + (t.slug || '[' + i + ']');
    if (!isStr(t.slug) || !SLUG.test(t.slug)) fail(w, '"slug" must be kebab-case');
    ['de', 'en', 'metaDescription'].forEach((k) => { if (!isStr(t[k])) fail(w, 'no "' + k + '"'); });
    if (t.aliases != null && !isStrArr(t.aliases)) fail(w, '"aliases" must be an array of strings');
    if (t.related != null) {
      if (!isStrArr(t.related)) fail(w, '"related" must be an array of strings');
      else t.related.forEach((r) => {
        if (r === t.slug) fail(w, 'lists itself in "related"');
        else if (!slugs.has(r)) fail(w, '"related" names "' + r + '", which has no topic page');
      });
    }
    ['rules', 'examples'].forEach((k) => { if (t[k] != null && !isStrArr(t[k])) fail(w, '"' + k + '" must be an array of strings'); });
    (t.sections || []).forEach((s, j) => { if (!isStr(s.h2)) fail(w + ' sections[' + j + ']', 'no "h2"'); });
    (t.faq || []).forEach((f, j) => { if (!isStr(f.q) || !isStr(f.a)) fail(w + ' faq[' + j + ']', 'needs "q" and "a"'); });
    (t.practice || []).forEach((p, j) => checkChoice(p, w + ' practice[' + j + ']'));
    (t.practiceGroups || []).forEach((g, j) => {
      if (!isStr(g.title)) fail(w + ' practiceGroups[' + j + ']', 'no "title"');
      if (!Array.isArray(g.items) || !g.items.length) fail(w + ' practiceGroups[' + j + ']', 'no "items"');
      else g.items.forEach((it, k) => checkChoice(it, w + ' practiceGroups[' + j + '].items[' + k + ']'));
    });
  });
}

const NUMBER_WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty'];

function quizzes() {
  const F = 'data/quizzes.json';
  const list = read(F);
  if (!Array.isArray(list)) return fail(F, 'must be an array');
  checkUnique(list, 'slug', F);
  list.forEach((z, i) => {
    const w = F + ' ' + (z.slug || '[' + i + ']');
    ['slug', 'unit', 'title', 'sub', 'description', 'canonical'].forEach((k) => { if (!isStr(z[k])) fail(w, 'no "' + k + '"'); });
    if (isStr(z.slug) && z.canonical !== SITE + '/quiz-' + z.slug + '.html') {
      fail(w, '"canonical" should be ' + SITE + '/quiz-' + z.slug + '.html');
    }
    if (!Array.isArray(z.questions) || !z.questions.length) return fail(w, 'no "questions"');
    z.questions.forEach((q, j) => checkChoice(q, w + ' q' + (j + 1)));
    // The copy states the count in words; it has drifted from the list before.
    const n = z.questions.length;
    ['sub', 'description'].forEach((k) => {
      const m = String(z[k] || '').toLowerCase().match(new RegExp('\\b(' + NUMBER_WORDS.join('|') + '|\\d+)\\b(?=[^.]*\\bquestions\\b)'));
      if (!m) return;
      const said = /^\d+$/.test(m[1]) ? Number(m[1]) : NUMBER_WORDS.indexOf(m[1]);
      if (said !== n) fail(w, '"' + k + '" says ' + m[1] + ' questions, the quiz has ' + n);
    });
  });
}

function exercises() {
  const F = 'data/exercises.json';
  const list = read(F);
  if (!Array.isArray(list)) return fail(F, 'must be an array');
  checkUnique(list, 'file', F);
  const topicSlugs = new Set(read('data/topics.json').map((t) => t.slug));
  const skills = new Set(Object.keys(SKILL_LABELS));
  list.forEach((e, i) => {
    const w = F + ' ' + (e.file || '[' + i + ']');
    if (!isStr(e.file) || !fs.existsSync(path.join(ROOT, e.file))) fail(w, 'no such page');
    if (!isStr(e.title)) fail(w, 'no "title"');
    if (!(Number.isInteger(e.year) || isStr(e.year))) fail(w, '"year" must be a number or a category name');
    if (!isStr(e.schoolType)) fail(w, 'no "schoolType"');
    if (!['en', 'de'].includes(String(e.lang).slice(0, 2))) fail(w, '"lang" should be en or de');
    if (!Array.isArray(e.topics)) fail(w, '"topics" must be an array');
    else e.topics.forEach((t) => { if (!topicSlugs.has(t)) fail(w, 'topic "' + t + '" has no entry in data/topics.json'); });
    if (!Array.isArray(e.skills)) fail(w, '"skills" must be an array');
    else e.skills.forEach((s) => { if (!skills.has(s)) fail(w, 'unknown skill "' + s + '"'); });
  });
}

const built = process.argv.includes('--built');
if (built) exercises(); else { topics(); quizzes(); }

if (errors.length) {
  errors.forEach((e) => console.error('✗ ' + e));
  console.error('\nvalidate-data: ' + errors.length + ' error(s)');
  process.exit(1);
}
console.log('validate-data: ' + (built ? 'data/exercises.json' : 'data/topics.json and data/quizzes.json') + ' — no errors');
